.TH ppthtml 1 "October 13, 2001" "ppthtml"

.SH NAME
ppthtml \- A program for converting Microsoft Power Point Files .ppt

.SH SYNOPSIS
.B ppthtml
.RI Filename
.br

.SH DESCRIPTION
This manual page explains the
.B ppthtml
program. The program
.B ppthtml
is used to convert Microsoft Power Point files into either html or tab delimitted ASCII. The program can be interfaced with helper scripts for viewing email attachments. Most use of this program is through the helper scripts and one would probably rarely resort to using the commandline interface.

.SH NOTES
To interface to Netscape Navigator: first locate the help scripts nspptview & nsopen. Go into the Edit Preferences dialog box. Click on the Navigator Category and hilight the Applications menu item. Look for Microsoft Excel Worksheet. If you don't see it create one. The MIME type should be:  application/vnd.ms-powerpoint  The suffixes should be: ppt,ppa,pps,pot,pwz  In the handled by section of the dialog box, check the Application checkbox and set the path to wherever the nspptview helper script is located and pass a %s argument. For example, if nspptview is located in /usr/local/bin, then you would put: 

/usr/local/bin/nspptview %s  

in the Application path box.. (As a side note, make sure the nspptview script can find the ppthtml program or it won't work.)  Click on the OK and you are done. You should be able to use the Test.ppt file that is distributed with the program to verify its configured correctly.

.SH AUTHOR
Charles N Wyble
