orestar_url: 'https://secure.sos.state.or.us/orestar/gotoPublicTransactionSearch.do'
search_form_name: cneSearchForm
start_date_field: cneSearchTranStartDate
end_date_field: cneSearchTranEndDate
date_format: "%m/%d/%Y"
search_button_name: search
file_download_href: XcelCNESearch
download_location: downloads/
